/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ILucideChevronRight: typeof import('~icons/lucide/chevron-right.jsx')['default']
  const ILucidePlus: typeof import('~icons/lucide/plus.jsx')['default']
  const ILucideX: typeof import('~icons/lucide/x.jsx')['default']
  const IMyLoading: typeof import('~icons/my/loading.jsx')['default']
}
